name: Build macOS Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build application
        run: |
          pyinstaller --onefile your_script.py

      - name: Create DMG
        run: |
          hdiutil create -volname YourAppName -srcfolder dist/ -ov -format UDZO YourAppName.dmg

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: 純白文本編輯器.dmg
          path: 純白文本編輯器三框版.py
